apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-client
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: client
spec:
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: demo-client:1.0.0
        command:
          - "/bin/sleep"
        args:
          - "99999999"
      serviceAccountName: vault-client
