apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: echo
spec:
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        command:
          - "/bin/sh"
        args:
          - "-c"
          - "while true; do nc -l -p 7 -e cat; done"
---
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  selector:
    app: echo
  ports:
    - port: 7
