apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: vault
spec:
  groups:
    - system:authenticated
  request: $CSR
  usages:
    - digital signature
    - key encipherment
    - server auth
