apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vault
spec:
  template:
    metadata:
      labels:
        app: vault-app
    spec:
      containers:
      - name: vault-container
        image: vault:0.8.3
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        volumeMounts:
          - name: vault-cert
            mountPath: /var/run/secrets/vault-cert
            readOnly: true
          - name: vault-config
            mountPath: /vault/config
            readOnly: false
        command: ["/bin/sh"]
        args: ["-c", "/bin/vault server -config=/vault/config"]
      volumes:
      - name: vault-cert
        secret:
          secretName: vault-cert
      - name: vault-config
        configMap:
          name: vault-config
---
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  selector:
    app: vault-app
  ports:
    - port: 8200
