---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vault
spec:
  template:
    metadata:
      labels:
        app: vault-app
    spec:
      containers:
      - name: vault-container
        image: demo-vault:0.9.0
        livenessProbe:
          httpGet:
            path: /v1/sys/health?uninitcode=200&sealedcode=200
            port: 8200
            scheme: HTTPS
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        volumeMounts:
          - name: vault-storage
            mountPath: /var/lib/vault
          - name: vault-cert
            mountPath: /var/run/secrets/vault-cert
            readOnly: true
          - name: vault-config
            mountPath: /etc/vault
            readOnly: true
      volumes:
      - name: vault-storage
        persistentVolumeClaim:
          claimName: vault-pvc
      - name: vault-config
        configMap:
          name: vault-config
      - name: vault-cert
        secret:
          secretName: vault-cert
      serviceAccountName: vault-auth
---
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  selector:
    app: vault-app
  ports:
    - port: 8200
