apiVersion: v1
kind: Pod
metadata:
  name: keycloak
  labels:
    app: keycloak-app

spec:
  volumes:
    - name: keycloak-persistent-data
      emptyDir: {}

  containers:
    - name: keycloak-container
      image: jboss/keycloak

      volumeMounts:
        - name: keycloak-persistent-data
          mountPath: /opt/jboss/keycloak/standalone/data

      env:
        - name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: username
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: password
        - name: PROXY_ADDRESS_FORWARDING
          value: true

# todo nginx reverse proxy for https

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  type: NodePort
  selector:
    app: keycloak-app
  ports:
    - port: 8080
