apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vault
spec:
  template:
    metadata:
      labels:
        app: vault-app
    spec:
      containers:
      - name: vault-container
        image: vault:0.7.2
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: my-root-token
---
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  selector:
    app: vault-app
  ports:
    - port: 8200
